# Generated by Django 4.2.7 on 2023-11-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='username',
            new_name='name',
        ),
    ]
